"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "carModels",
      [
        {
          modelName: "R8",
          imageUrl: "url.audi.r8",
          soundUrl: "url.audi.r8sound",
          capacity: 3000,
          fuel: 12,
          acceleration: 3.2,
          carPrice: 100000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 1,
        },
        {
          modelName: "rs3",
          imageUrl: "url.audi.rs3",
          soundUrl: "url.audi.rs3sound",
          capacity: 2400,
          fuel: 8.3,
          acceleration: 6.3,
          carPrice: 120000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 1,
        },
        {
          modelName: "s500",
          imageUrl: "url.benz.s500",
          soundUrl: "url.benz.s500sound",
          capacity: 3000,
          fuel: 11,
          acceleration: 7.3,
          carPrice: 230000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 2,
        },
        {
          modelName: "730li",
          imageUrl: "url.bmw.730li",
          soundUrl: "url.bmw.730lisound",
          capacity: 2600,
          fuel: 9.2,
          acceleration: 7.3,
          carPrice: 210000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 3,
        },
        {
          modelName: "x6",
          imageUrl: "url.bmw.x6",
          soundUrl: "url.bmw.x6sound",
          capacity: 3500,
          fuel: 13.1,
          acceleration: 8.3,
          carPrice: 300000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 3,
        },
        {
          modelName: "urus",
          imageUrl: "url.bmw.urus",
          soundUrl: "url.bmw.urussound",
          capacity: 3500,
          fuel: 14.1,
          acceleration: 5.3,
          carPrice: 310000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 4,
        },
        {
          modelName: "avantador",
          imageUrl: "url.bmw.avantador",
          soundUrl: "url.bmw.avantadorsound",
          capacity: 3500,
          fuel: 14.5,
          acceleration: 3.3,
          carPrice: 500000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 4,
        },
        {
          modelName: "horakan",
          imageUrl: "url.bmw.horakan",
          soundUrl: "url.bmw.horakansound",
          capacity: 3300,
          fuel: 14.5,
          acceleration: 3.2,
          carPrice: 442000,
          createdAt: new Date(),
          updatedAt: new Date(),
          carBrandId: 4,
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("carModels", null, {});
  },
};
